USE [master]
GO

CREATE DATABASE [GrapeERP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GrapeERP', FILENAME = N'DatabasePath\GrapeERP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [COMMERCIAL] 
( NAME = N'GrapeERP_Commercial', FILENAME = N'DatabasePath\GrapeERP_Commercial.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [DEFINITIONS] 
( NAME = N'GrapeERP_DefinitionTables', FILENAME = N'DatabasePath\GrapeERP_DefinitionTables.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [LOG] 
( NAME = N'GrapeERP_LogTables', FILENAME = N'DatabasePath\GrapeERP_LogTables.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [MANUFACTURE] 
( NAME = N'GrapeERP_Manufacture', FILENAME = N'DatabasePath\GrapeERP_Manufacture.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [STOCK] 
( NAME = N'GrapeERP_StockTables', FILENAME = N'DatabasePath\GrapeERP_StockTables.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GrapeERP_log', FILENAME = N'DatabasePath\GrapeERP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GrapeERP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GrapeERP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GrapeERP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GrapeERP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GrapeERP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GrapeERP] SET ARITHABORT OFF 
GO

ALTER DATABASE [GrapeERP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GrapeERP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GrapeERP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GrapeERP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GrapeERP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GrapeERP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GrapeERP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GrapeERP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GrapeERP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GrapeERP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GrapeERP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GrapeERP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GrapeERP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GrapeERP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GrapeERP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GrapeERP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GrapeERP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GrapeERP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GrapeERP] SET  MULTI_USER 
GO

ALTER DATABASE [GrapeERP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GrapeERP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GrapeERP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GrapeERP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GrapeERP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GrapeERP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GrapeERP] SET  READ_WRITE 
GO


